import React, { useEffect, useRef, useState } from "react";
import { ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts";
import jsPDF from "jspdf";
import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory } from "@capacitor/filesystem";
import { FileOpener } from "@capacitor-community/file-opener";
import { api } from "../../lib/api";
import { ScreenHeader, PageContainer, Spinner, Empty, Toast, useToast } from "../ui/Shell";
import { fmtMoney, fmtMoneyCompact, fmtHours, fmtDateShort, durationHours } from "../../lib/format";
import { rechartsTooltipProps } from "../../lib/rechartsTooltipProps";
import { Download, FileText } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { UPSELL_EVENT } from "../UpsellModal";
import { TimeEntryEditorSheet } from "./TimeEntryEditorSheet";

const LS_OPEN_URI = "bm_last_report_open_uri";
const LS_DISPLAY = "bm_last_report_display";

// Free-plan quota: 3 PDFs per calendar month. Pro is unlimited. Tracked locally — RootRecord
// Business Manager is local-first and the quota is a soft fairness cap, not a security boundary.
// Pro entitlement still comes from the auth context (`user?.plan === "pro"`).
const PDF_QUOTA_FREE = 3;
function pdfQuotaKey() {
  const d = new Date();
  return `bm.pdf_quota.${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
}
function readPdfCount() {
  if (typeof localStorage === "undefined") return 0;
  try {
    return Math.max(0, Number(localStorage.getItem(pdfQuotaKey()) || 0));
  } catch {
    return 0;
  }
}
function incPdfCount() {
  if (typeof localStorage === "undefined") return 0;
  try {
    const n = readPdfCount() + 1;
    localStorage.setItem(pdfQuotaKey(), String(n));
    return n;
  } catch {
    return readPdfCount();
  }
}

/** Convert "#RRGGBB" / "#RGB" → [r, g, b]; returns null if unparseable so callers can fall back. */
function hexToRgb(hex) {
  if (!hex || typeof hex !== "string") return null;
  const m = hex.replace("#", "").trim();
  if (m.length === 3) {
    return [parseInt(m[0] + m[0], 16), parseInt(m[1] + m[1], 16), parseInt(m[2] + m[2], 16)];
  }
  if (m.length === 6) {
    return [parseInt(m.slice(0, 2), 16), parseInt(m.slice(2, 4), 16), parseInt(m.slice(4, 6), 16)];
  }
  return null;
}

/**
 * Render a "Time Keeping Sheet" PDF that visually matches the HTML mockup the user signed off on
 * (green accent header, three-up meta row, detailed table, summary-by-category table, totals box,
 * signature lines, footer). Pure jsPDF — no headless HTML renderer needed, so it works identically
 * on web and on Capacitor Android.
 *
 * jsPDF coordinates here are in millimetres on an A4 portrait page (210 × 297 mm) with a 15 mm
 * page margin. Built-in `times` is used for serif headings (Instrument-Serif look) and `helvetica`
 * for sans-serif body — both are bundled with jsPDF so the PDF renders without web-font fetches.
 */
function buildTimeKeepingPdf({
  entries,
  cats,
  breakdown,
  start,
  end,
  employee,
  business,
  preparedDate,
  fmtHoursArg,
  fmtDateShortArg,
  durationHoursArg,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const PAGE_W = 210;
  const PAGE_H = 297;
  const MARGIN = 15;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  // Colors lifted from the user's HTML template (`--accent`, `--text`, etc).
  const ACCENT = [22, 101, 52]; // #166534
  const TEXT = [26, 26, 26]; // #1a1a1a
  const SOFT = [74, 74, 74]; // #4a4a4a
  const LINE = [229, 226, 222]; // #e5e2de
  const TINT = [248, 246, 243]; // #f8f6f3

  function setText(rgb) {
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  }
  function setFill(rgb) {
    doc.setFillColor(rgb[0], rgb[1], rgb[2]);
  }
  function setDraw(rgb) {
    doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
  }
  /** Footer + page number on every page; called after the last write. */
  function paintFooters() {
    const pages = doc.getNumberOfPages();
    for (let p = 1; p <= pages; p++) {
      doc.setPage(p);
      setDraw(LINE);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, PAGE_H - 14, PAGE_W - MARGIN, PAGE_H - 14);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      setText(SOFT);
      doc.text(
        "Generated by RootRecord Business Manager • rootrecord.info • Local-first • Secure by design",
        PAGE_W / 2,
        PAGE_H - 10,
        { align: "center" }
      );
      doc.text(
        "This document is for record-keeping purposes. All data is stored locally unless online backup is enabled.",
        PAGE_W / 2,
        PAGE_H - 6,
        { align: "center" }
      );
      doc.text(`Page ${p} / ${pages}`, PAGE_W - MARGIN, PAGE_H - 6, { align: "right" });
    }
  }
  /** Reserve at least `needed` mm of remaining vertical space; add a page if not. */
  function ensureSpace(cur, needed) {
    if (cur + needed > PAGE_H - 22) {
      doc.addPage();
      return MARGIN;
    }
    return cur;
  }

  let y = MARGIN;

  // ---- HEADER ----
  doc.setFont("times", "normal");
  doc.setFontSize(26);
  setText(ACCENT);
  doc.text("RootRecord", MARGIN, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setText(SOFT);
  doc.text("Business Manager • Time & Operations", MARGIN, y + 14);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setText(TEXT);
  doc.text("rootrecord.info", PAGE_W - MARGIN, y + 6, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setText(SOFT);
  doc.text("Professional Time Keeping Sheet", PAGE_W - MARGIN, y + 12, { align: "right" });

  y += 18;
  setDraw(ACCENT);
  doc.setLineWidth(0.9);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 10;

  // ---- TITLE ----
  doc.setFont("times", "normal");
  doc.setFontSize(22);
  setText(TEXT);
  doc.text("Time Keeping Sheet", PAGE_W / 2, y, { align: "center" });
  y += 10;

  // ---- COMPANY (left)  +  PERIOD / PREPARED (right) ----
  // The active business profile is the source of truth. If business settings aren't loaded yet
  // (e.g. guest or first run) we still render the period / prepared block on the right.
  const b = business || {};
  const companyName = (b.name || "").trim();
  const ownerLine = [b.legal_name, b.owner].filter((v) => v && String(v).trim()).filter((v, i, a) => a.indexOf(v) === i).join(" · ");
  // Build a flat list of contact lines we know about, in display order; trim and skip blanks so
  // the block collapses gracefully when fields are empty.
  const contactLines = [
    b.address,
    [b.phone, b.email].filter(Boolean).join("  ·  "),
    b.website,
    b.tax_id ? `Tax ID: ${b.tax_id}` : "",
  ].map((s) => (s || "").toString().trim()).filter(Boolean);

  const leftX = MARGIN;
  const rightX = PAGE_W - MARGIN;
  const blockTop = y;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setText(SOFT);
  doc.text("FROM", leftX, blockTop);
  let yL = blockTop + 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  setText(TEXT);
  doc.text(companyName || employee || "—", leftX, yL);
  yL += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  setText(SOFT);
  if (ownerLine) {
    doc.text(ownerLine, leftX, yL);
    yL += 4.2;
  }
  for (const line of contactLines) {
    // jsPDF.splitTextToSize keeps the address from running into the right column.
    const wrapped = doc.splitTextToSize(line, 100);
    doc.text(wrapped, leftX, yL);
    yL += wrapped.length * 4.2;
  }

  // Right column: PERIOD on top, PREPARED ON under it. Right-aligned so it reads as a stamp.
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setText(SOFT);
  doc.text("PERIOD", rightX, blockTop, { align: "right" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setText(TEXT);
  doc.text(`${start} — ${end}`, rightX, blockTop + 5, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setText(SOFT);
  doc.text("PREPARED ON", rightX, blockTop + 12, { align: "right" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setText(TEXT);
  doc.text(preparedDate, rightX, blockTop + 17, { align: "right" });

  // Reserve the taller of the two columns so the table never overlaps either block.
  const yR = blockTop + 21;
  y = Math.max(yL, yR) + 6;

  // ---- DETAIL TABLE ----
  // Column geometry: Date (28) · Category (32) · Description (flex) · Hours (20 right-aligned)
  const cDate = MARGIN;
  const cCat = MARGIN + 28;
  const cDesc = MARGIN + 60;
  const cHrs = PAGE_W - MARGIN; // right edge for right-aligned hours
  const rowH = 6.5;
  const headH = 7;

  function drawTableHeader(headers) {
    setFill(TINT);
    doc.rect(MARGIN, y, CONTENT_W, headH, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    setText(ACCENT);
    headers.forEach((h) => doc.text(h.label, h.x, y + 4.8, h.opts || {}));
    y += headH;
  }

  const detailHeader = [
    { label: "DATE", x: cDate + 1 },
    { label: "CATEGORY", x: cCat + 1 },
    { label: "DESCRIPTION / TASK", x: cDesc + 1 },
    { label: "HOURS", x: cHrs - 1, opts: { align: "right" } },
  ];
  drawTableHeader(detailHeader);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setText(TEXT);
  setDraw(LINE);
  doc.setLineWidth(0.2);

  const sortedEntries = [...entries].sort((a, b) => String(a.start_utc).localeCompare(String(b.start_utc)));
  for (const e of sortedEntries) {
    const date = fmtDateShortArg(e.start_utc) || "—";
    const catName = cats[e.category_id]?.name || "—";
    const desc = (e.description || cats[e.category_id]?.name || "Time entry").toString();
    const hrs = fmtHoursArg(durationHoursArg(e.start_utc, e.end_utc) || 0);
    // jsPDF.splitTextToSize wraps the description to the available column width.
    const descWrapped = doc.splitTextToSize(desc, cHrs - cDesc - 22);
    const usedRowH = Math.max(rowH, descWrapped.length * 4 + 2);
    // Reserve the row's ACTUAL height (not just the minimum), otherwise long wrapped descriptions
    // push subsequent rows below the page bottom — jsPDF won't auto-flow, so those rows render
    // off-page and silently vanish. After a page break, redraw the column header so the new page
    // remains self-describing.
    const before = y;
    y = ensureSpace(y, usedRowH);
    if (y !== before) {
      drawTableHeader(detailHeader);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      setText(TEXT);
      setDraw(LINE);
      doc.setLineWidth(0.2);
    }
    doc.text(String(date), cDate + 1, y + 4.5);
    doc.text(String(catName).slice(0, 18), cCat + 1, y + 4.5);
    doc.text(descWrapped, cDesc + 1, y + 4.5);
    doc.text(String(hrs), cHrs - 1, y + 4.5, { align: "right" });
    doc.line(MARGIN, y + usedRowH, PAGE_W - MARGIN, y + usedRowH);
    y += usedRowH;
  }
  if (sortedEntries.length === 0) {
    doc.setFont("helvetica", "italic");
    setText(SOFT);
    doc.text("No time entries in this period.", PAGE_W / 2, y + 5, { align: "center" });
    doc.setFont("helvetica", "normal");
    setText(TEXT);
    y += rowH;
  }
  setDraw(ACCENT);
  doc.setLineWidth(0.6);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 12;

  // ---- TIME DISTRIBUTION (pie chart + legend) ----
  // The summary table below gives exact numbers; this section gives the at-a-glance shape of
  // where the time went. Vector-drawn (jsPDF polygons) so no canvas/screenshot dance is needed —
  // works identically on web and Capacitor Android.
  const totalHrsForChart = breakdown.reduce((s, b) => s + (Number(b.hours) || 0), 0);
  if (breakdown.length > 0 && totalHrsForChart > 0) {
    y = ensureSpace(y, 70);
    doc.setFont("times", "normal");
    doc.setFontSize(14);
    setText(ACCENT);
    doc.text("Time Distribution", MARGIN, y);
    y += 6;

    const radius = 22;
    const cx = MARGIN + radius + 5;
    const cy = y + radius + 2;
    // Walk slices clockwise from top (-π/2). For each slice build a polygon "fan": center →
    // sampled arc points → implicit close back to center. ~10° per segment keeps edges smooth
    // without blowing up the PDF size.
    let angle = -Math.PI / 2;
    for (const slice of breakdown) {
      const frac = (Number(slice.hours) || 0) / totalHrsForChart;
      if (frac <= 0) continue;
      const sweep = frac * Math.PI * 2;
      const segs = Math.max(2, Math.ceil(sweep / (Math.PI / 18)));
      const deltas = [];
      let prev = [0, 0];
      for (let i = 0; i <= segs; i++) {
        const a = angle + (sweep * i) / segs;
        const px = Math.cos(a) * radius;
        const py = Math.sin(a) * radius;
        deltas.push([px - prev[0], py - prev[1]]);
        prev = [px, py];
      }
      const rgb = hexToRgb(slice.color) || [120, 120, 120];
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(0.4);
      // jsPDF.lines(deltas, originX, originY, scale, style, closed=true).
      doc.lines(deltas, cx, cy, [1, 1], "FD", true);
      angle += sweep;
    }

    // Legend column to the right of the chart.
    const legendX = MARGIN + radius * 2 + 14;
    const legendValueX = PAGE_W - MARGIN;
    let legendY = y + 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    for (const slice of breakdown) {
      const pct = ((Number(slice.hours) || 0) / totalHrsForChart) * 100;
      const rgb = hexToRgb(slice.color) || [120, 120, 120];
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(legendX, legendY - 3, 3, 3, "F");
      setText(TEXT);
      doc.text(String(slice.name), legendX + 5, legendY);
      setText(SOFT);
      doc.text(
        `${fmtHoursArg(Number(slice.hours) || 0)} · ${pct.toFixed(0)}%`,
        legendValueX,
        legendY,
        { align: "right" }
      );
      legendY += 5;
    }

    // Advance past whichever column is taller.
    y = Math.max(cy + radius + 4, legendY) + 6;
  }

  // ---- SUMMARY BY CATEGORY ----
  y = ensureSpace(y, 60);
  doc.setFont("times", "normal");
  doc.setFontSize(14);
  setText(ACCENT);
  doc.text("Summary by Category", MARGIN, y);
  y += 5;

  const sumCat = MARGIN;
  const sumHrs = MARGIN + 110;
  const sumPct = PAGE_W - MARGIN;
  drawTableHeader([
    { label: "CATEGORY", x: sumCat + 1 },
    { label: "HOURS", x: sumHrs - 1, opts: { align: "right" } },
    { label: "PERCENTAGE", x: sumPct - 1, opts: { align: "right" } },
  ]);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setText(TEXT);
  setDraw(LINE);

  const totalHrs = breakdown.reduce((s, b) => s + (Number(b.hours) || 0), 0);
  const safeTotal = totalHrs > 0 ? totalHrs : 1;
  for (const b of breakdown) {
    y = ensureSpace(y, rowH + 4);
    const pct = ((Number(b.hours) || 0) / safeTotal) * 100;
    doc.text(String(b.name), sumCat + 1, y + 4.5);
    doc.text(fmtHoursArg(Number(b.hours) || 0), sumHrs - 1, y + 4.5, { align: "right" });
    doc.text(`${pct.toFixed(0)}%`, sumPct - 1, y + 4.5, { align: "right" });
    doc.line(MARGIN, y + rowH, PAGE_W - MARGIN, y + rowH);
    y += rowH;
  }
  setFill(TINT);
  doc.rect(MARGIN, y, CONTENT_W, rowH + 1, "F");
  doc.setFont("helvetica", "bold");
  setText(TEXT);
  doc.text("TOTAL HOURS", sumCat + 1, y + 5);
  doc.text(fmtHoursArg(totalHrs), sumHrs - 1, y + 5, { align: "right" });
  doc.text("100%", sumPct - 1, y + 5, { align: "right" });
  y += rowH + 1;
  setDraw(ACCENT);
  doc.setLineWidth(0.6);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 12;

  // ---- TOTAL BOX (billable + grand total) ----
  // Billable hours = sum of entry hours where cats[category_id].billable === 1.
  let billableHrs = 0;
  for (const e of sortedEntries) {
    if (Number(cats[e.category_id]?.billable) === 1) {
      billableHrs += Number(durationHoursArg(e.start_utc, e.end_utc) || 0);
    }
  }
  y = ensureSpace(y, 24);
  const boxH = 20;
  setFill(TINT);
  setDraw(ACCENT);
  doc.setLineWidth(0.6);
  doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2.5, 2.5, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setText(TEXT);
  doc.text("Total Billable Hours:", MARGIN + 5, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setText(SOFT);
  doc.text(`${fmtHoursArg(billableHrs)}`, MARGIN + 5, y + 14);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  setText(ACCENT);
  doc.text(`${fmtHoursArg(totalHrs)} hours`, PAGE_W - MARGIN - 5, y + 13, { align: "right" });
  y += boxH + 18;

  // ---- SIGNATURES ----
  y = ensureSpace(y, 22);
  const sigW = 70;
  setDraw([60, 60, 60]);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, MARGIN + sigW, y);
  doc.line(PAGE_W - MARGIN - sigW, y, PAGE_W - MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setText(TEXT);
  doc.text("Employee Signature / Approval", MARGIN, y + 5);
  doc.text("Manager / Client Approval", PAGE_W - MARGIN, y + 5, { align: "right" });

  paintFooters();
  return doc;
}

export default function Reports() {
  const { guest, user } = useAuth();
  const today = new Date();
  const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);
  const [start, setStart] = useState(monthStart.toISOString().slice(0, 10));
  const [end, setEnd] = useState(today.toISOString().slice(0, 10));
  const [data, setData] = useState(null);
  const [entries, setEntries] = useState([]);
  const [cats, setCats] = useState({});
  // `business` is the active Business Settings profile — the canonical source for the PDF's
  // FROM block (name, owner, legal name, address, phone, email, website, tax ID).
  const [business, setBusiness] = useState(null);
  const [loading, setLoading] = useState(false);
  const [editEntry, setEditEntry] = useState(null);
  const { toast, show, clear } = useToast();

  const lastWebPdfUrlRef = useRef(null);
  const [lastReportDisplay, setLastReportDisplay] = useState(() => {
    if (typeof localStorage === "undefined") return "";
    if (Capacitor.isNativePlatform()) return localStorage.getItem(LS_DISPLAY) || "";
    return "";
  });
  const [hasNativeLast, setHasNativeLast] = useState(() =>
    typeof localStorage !== "undefined" && Capacitor.isNativePlatform() ? Boolean(localStorage.getItem(LS_OPEN_URI)) : false
  );
  const [hasWebLast, setHasWebLast] = useState(false);

  const isPro = user?.plan === "pro";
  const [pdfCount, setPdfCount] = useState(() => readPdfCount());
  const pdfRemaining = Math.max(0, PDF_QUOTA_FREE - pdfCount);
  const quotaUsedUp = !isPro && pdfRemaining <= 0;

  useEffect(() => {
    return () => {
      if (lastWebPdfUrlRef.current) {
        URL.revokeObjectURL(lastWebPdfUrlRef.current);
        lastWebPdfUrlRef.current = null;
      }
    };
  }, []);

  async function load() {
    if (guest) return;
    setLoading(true);
    try {
      const sIso = new Date(`${start}T00:00:00`).toISOString();
      const eIso = new Date(`${end}T23:59:59`).toISOString();
      // /businesses is fetched alongside the summary so the PDF FROM block reflects the latest
      // Business Settings without needing the user to revisit that screen. First row wins, same
      // selection rule BusinessSettings itself uses.
      const [{ data: sum }, { data: rows }, { data: catRows }, bizRes] = await Promise.all([
        api.get("/dashboard/summary", { params: { start: sIso, end: eIso } }),
        api.get("/time/entries", { params: { start: sIso, end: eIso } }),
        api.get("/categories"),
        api.get("/businesses").catch(() => ({ data: [] })),
      ]);
      setData(sum);
      setEntries(Array.isArray(rows) ? rows : []);
      const catList = Array.isArray(catRows) ? catRows : [];
      setCats(Object.fromEntries(catList.map((c) => [c.id, c])));
      const bizList = Array.isArray(bizRes?.data) ? bizRes.data : [];
      setBusiness(bizList.find((x) => x?.is_default) || bizList[0] || null);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => {
    load();
  }, []); // eslint-disable-line

  async function downloadPdf() {
    if (!data) return;
    // Standard-plan gate: ignore the entry count, gate on monthly PDF quota instead.
    // The upsell modal explains the cap and offers a membership path without blocking the UI.
    if (!isPro && readPdfCount() >= PDF_QUOTA_FREE) {
      try { window.dispatchEvent(new Event(UPSELL_EVENT)); } catch { /* ignore */ }
      show(`Standard access: ${PDF_QUOTA_FREE} reports per month. More reports are limited to members only.`, "warn");
      return;
    }
    const filename = `rootrecord-timesheet-${start}-${end}.pdf`;
    const breakdown = Array.isArray(data.breakdown) ? data.breakdown : [];
    // Prefer the business profile's owner/legal name; fall back to the signed-in account so the
    // PDF still has a defensible "from" identity if Business Settings is empty.
    const employee = (
      business?.owner ||
      business?.legal_name ||
      business?.name ||
      user?.full_name ||
      user?.name ||
      user?.email ||
      "Employee / Contractor"
    ).toString();
    const preparedDate = new Date().toISOString().slice(0, 10);

    const doc = buildTimeKeepingPdf({
      entries,
      cats,
      breakdown,
      start,
      end,
      employee,
      business,
      preparedDate,
      fmtHoursArg: fmtHours,
      fmtDateShortArg: fmtDateShort,
      durationHoursArg: durationHours,
    });

    try {
      if (Capacitor.isNativePlatform()) {
        // Storage strategy on Android:
        //   - `Directory.External` maps to `getExternalFilesDir()` —
        //     `/Android/data/<package>/files/...`. App-specific external storage:
        //       * No runtime permission needed on any Android version (Capacitor 6, Android 10+).
        //       * Already declared in Capacitor's default FileProvider (`external-files-path`),
        //         so `FileOpener.open(uri)` works and ACTION_VIEW hands the PDF to any installed
        //         viewer without "permission denied" or FileProvider errors.
        //       * Visible in the device's file manager under `Android/data/<package>/files/RootRecord/`.
        //   - `Directory.Documents` was attempted first but hits scoped-storage write permission
        //     on Android 11+ unless the app declares MANAGE_EXTERNAL_STORAGE (heavy + Play-policy risk).
        //   - `Directory.Data` is app-internal and not exposed by the default FileProvider, so
        //     FileOpener silently fails to hand off in some Android builds.
        const base64 = doc.output("datauristring").split(",")[1];
        const path = `RootRecord/${filename}`;
        const { uri } = await Filesystem.writeFile({
          path,
          data: base64,
          directory: Directory.External,
          recursive: true,
        });
        const display = `Android/data/com.rootrecord.businessmanager/files/${path}`;
        localStorage.setItem(LS_OPEN_URI, uri);
        localStorage.setItem(LS_DISPLAY, display);
        setLastReportDisplay(display);
        setHasNativeLast(true);
        if (!isPro) setPdfCount(incPdfCount());
        show(`PDF saved — opening…`, "success");
        // Open immediately on save: the user's intent is "make + view", and not auto-opening was
        // a big source of "the mobile fails to load it" reports. Failures here are non-fatal —
        // the saved file still exists and the "Open Last Report" button can retry.
        try {
          await FileOpener.open({
            filePath: uri,
            contentType: "application/pdf",
            openWithDefault: true,
          });
        } catch (openErr) {
          console.warn("auto-open after save failed", openErr);
        }
      } else {
        if (lastWebPdfUrlRef.current) {
          URL.revokeObjectURL(lastWebPdfUrlRef.current);
        }
        const blob = doc.output("blob");
        const url = URL.createObjectURL(blob);
        lastWebPdfUrlRef.current = url;
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        a.rel = "noopener";
        document.body.appendChild(a);
        a.click();
        a.remove();
        const webLabel = `${filename} (browser download folder)`;
        setLastReportDisplay(webLabel);
        setHasWebLast(true);
        setHasNativeLast(false);
        if (!isPro) setPdfCount(incPdfCount());
        show(`PDF saved — ${webLabel}. “Open Last Report” opens a preview in a new tab.`, "success");
      }
    } catch (e) {
      console.error(e);
      show(e?.message || "Could not save PDF", "err");
    }
  }

  async function openLastReport() {
    try {
      if (Capacitor.isNativePlatform()) {
        const uri = localStorage.getItem(LS_OPEN_URI);
        if (!uri) {
          show("No saved report yet. Save a PDF first.", "warn");
          return;
        }
        await FileOpener.open({
          filePath: uri,
          contentType: "application/pdf",
          openWithDefault: true,
        });
      } else {
        const url = lastWebPdfUrlRef.current;
        if (!url) {
          show("No report in this session. Save a PDF again, then open.", "warn");
          return;
        }
        window.open(url, "_blank", "noopener,noreferrer");
      }
    } catch (e) {
      console.error(e);
      show(e?.message || "Could not open PDF", "err");
    }
  }

  const canOpenLast = Capacitor.isNativePlatform() ? hasNativeLast : hasWebLast;

  return (
    <>
      <ScreenHeader title="Reports" subtitle="Date-bound charts and downloadable summary" />
      <PageContainer>
        {guest ? (
          <Empty title="Sign in to view reports" />
        ) : (
          <>
            <div className="card p-3 mb-3 grid grid-cols-2 gap-2">
              <label className="block">
                <span className="label">Start</span>
                <input data-testid="reports-start" type="date" className="input" value={start} onChange={(e) => setStart(e.target.value)} />
              </label>
              <label className="block">
                <span className="label">End</span>
                <input data-testid="reports-end" type="date" className="input" value={end} onChange={(e) => setEnd(e.target.value)} />
              </label>
              <button data-testid="reports-load-btn" onClick={load} className="btn btn-primary col-span-2">
                Load range
              </button>
              <button
                data-testid="reports-pdf-btn"
                onClick={downloadPdf}
                disabled={!data}
                className="btn btn-secondary col-span-2"
                title={
                  isPro
                    ? ""
                    : quotaUsedUp
                    ? `Standard access: ${PDF_QUOTA_FREE} reports per month used up. More reports are limited to members only.`
                    : `Standard access: ${pdfRemaining} of ${PDF_QUOTA_FREE} reports remaining this month.`
                }
              >
                <Download size={16} /> Save time-keeping PDF
                {!isPro && (quotaUsedUp ? " (Members only after limit)" : ` (${pdfRemaining} of ${PDF_QUOTA_FREE} this month)`)}
              </button>
              <button
                type="button"
                data-testid="reports-open-last-btn"
                onClick={openLastReport}
                disabled={!canOpenLast}
                className="btn btn-secondary col-span-2"
                title={canOpenLast ? "Open the last saved PDF" : "Save a PDF first"}
              >
                <FileText size={16} /> Open Last Report
              </button>
              {lastReportDisplay ? (
                <p data-testid="reports-last-path" className="col-span-2 text-xs text-ink-tertiary break-all m-0 leading-relaxed">
                  <span className="text-ink-secondary font-medium">Last file: </span>
                  {lastReportDisplay}
                </p>
              ) : (
                <p className="col-span-2 text-xs text-ink-tertiary m-0">After you save, the path appears here.</p>
              )}
            </div>

            {loading ? (
              <Spinner />
            ) : !data ? (
              <Empty title="Pick a range and Load" />
            ) : (
              <>
                <div className="grid grid-cols-2 gap-2 mb-3">
                  <Mini label="Hours" value={fmtHours(data.hours)} />
                  <Mini label="Net" value={fmtMoneyCompact(data.net_cents)} fullValue={fmtMoney(data.net_cents)} accent={data.net_cents >= 0 ? "income" : "expense"} />
                  <Mini label="Income" value={fmtMoneyCompact(data.income_cents)} fullValue={fmtMoney(data.income_cents)} accent="income" />
                  <Mini label="Expenses" value={fmtMoneyCompact(data.expense_cents)} fullValue={fmtMoney(data.expense_cents)} accent="expense" />
                </div>

                {data.breakdown.length > 0 && (
                  <div className="card p-3 mb-3">
                    <p className="label mb-2">By category</p>
                    <div style={{ width: "100%", height: 200 }}>
                      <ResponsiveContainer>
                        <PieChart>
                          <Pie data={data.breakdown} dataKey="hours" nameKey="name" innerRadius={40} outerRadius={75} stroke="none">
                            {data.breakdown.map((b, i) => (
                              <Cell key={i} fill={b.color} />
                            ))}
                          </Pie>
                          <Tooltip {...rechartsTooltipProps} />
                        </PieChart>
                      </ResponsiveContainer>
                    </div>
                    <div style={{ width: "100%", height: 180 }} className="mt-1">
                      <ResponsiveContainer>
                        <BarChart data={data.breakdown} margin={{ top: 8, right: 8, left: -20, bottom: 8 }}>
                          <XAxis dataKey="name" tick={{ fill: "#687777", fontSize: 10 }} angle={-30} textAnchor="end" height={40} interval={0} />
                          <YAxis tick={{ fill: "#687777", fontSize: 10 }} />
                          <Tooltip {...rechartsTooltipProps} />
                          <Bar dataKey="hours" radius={[6, 6, 0, 0]}>
                            {data.breakdown.map((b, i) => (
                              <Cell key={i} fill={b.color} />
                            ))}
                          </Bar>
                        </BarChart>
                      </ResponsiveContainer>
                    </div>
                  </div>
                )}

                <div className="card overflow-hidden">
                  <div className="row" style={{ background: "rgba(255,255,255,0.03)" }}>
                    <span className="text-xs text-ink-tertiary uppercase tracking-widest">Entries</span>
                    <span className="text-xs text-ink-tertiary">{entries.length}</span>
                  </div>
                  {entries.length === 0 ? (
                    <p className="p-4 text-sm text-ink-tertiary text-center">No entries in this range.</p>
                  ) : (
                    entries.slice(0, 50).map((e) => {
                      const c = cats[e.category_id];
                      return (
                        <button
                          type="button"
                          key={e.id}
                          data-testid={`reports-entry-${e.id}`}
                          className="row w-full text-left border-0 bg-transparent cursor-pointer hover:bg-[rgba(255,255,255,0.03)]"
                          onClick={() => setEditEntry(e)}
                        >
                          <div className="min-w-0 pr-3 flex-1">
                            <p className="text-sm truncate">
                              {c && <span className="inline-block w-2 h-2 rounded-full mr-2" style={{ backgroundColor: c.color }} />}
                              {e.description || c?.name || "Time entry"}
                            </p>
                            <p className="text-xs text-ink-tertiary">
                              {fmtDateShort(e.start_utc)} · {fmtHours(durationHours(e.start_utc, e.end_utc))}
                            </p>
                          </div>
                        </button>
                      );
                    })
                  )}
                  {entries.length > 50 && (
                    <p className="p-3 text-xs text-ink-tertiary text-center">+{entries.length - 50} more (download PDF for full list)</p>
                  )}
                </div>
              </>
            )}
          </>
        )}
      </PageContainer>
      <Toast message={toast.message} kind={toast.kind} onDone={clear} />
      <TimeEntryEditorSheet
        open={Boolean(editEntry)}
        entry={editEntry}
        categories={Object.values(cats)}
        onClose={() => setEditEntry(null)}
        onSaved={() => load()}
        showToast={show}
        onTaxonomyRefresh={load}
      />
    </>
  );
}

function Mini({ label, value, fullValue, accent }) {
  const color = accent === "income" ? "text-income" : accent === "expense" ? "text-expense" : "text-ink-primary";
  return (
    <div className="card p-3 min-w-0">
      <p className="text-[10px] uppercase tracking-widest text-ink-tertiary">{label}</p>
      <p className={`font-heading text-lg font-bold ${color} truncate tabular-nums`} title={fullValue || value}>
        {value}
      </p>
    </div>
  );
}
