#!/usr/bin/env python3
"""
Emit SQL for Cloudflare D1 `bm_owned_row` from the legacy Windows / Electron
RootRecord Business Manager SQLite (`business_data/rootrecord.db`).

Stable row ids (uuid5 hex, 32 chars) so re-running the same import updates rows
instead of duplicating.

Usage:
  python import_windows_bm_sqlite.py \\
    --db "C:/Users/you/RootRecord/Business Manager/business_data/rootrecord.db" \\
    --email rootrecord@outlook.com \\
    --out import-bm.sql

Apply to remote D1 (with credentials in env, same as deploy.ps1):
  cd Web/cloudflare/rootrecord-primary
  npx wrangler d1 execute root-record --remote --file=scripts/import-bm.sql

Before first import, optionally wipe existing BM rows for that user:
  npx wrangler d1 execute root-record --remote --command=\\
    "DELETE FROM bm_owned_row WHERE user_key = 'user:rootrecord@outlook.com';"

Note: Do not wrap statements in BEGIN/COMMIT; remote D1 rejects explicit SQL transactions.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")  # UUID URL namespace


def stable_id(coll: str, old_pk: int) -> str:
    return uuid.uuid5(NS, f"rr:bm-import:v1|{coll}|{old_pk}").hex


def iso_z(raw: Optional[str]) -> str:
    if not raw or not str(raw).strip():
        return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    s = str(raw).strip()
    if s.endswith("Z"):
        return s
    if "+" in s or s.count("-") > 2 and "T" in s and s.endswith(("+00:00",)):
        return datetime.fromisoformat(s.replace("Z", "+00:00")).astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    # SQLite "2026-04-09T00:53:11.000" etc.
    if "T" in s and not s.endswith("Z"):
        return s + "Z" if not s.endswith("+00:00") else s.replace("+00:00", "Z")
    return s


def sql_escape(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_json(obj: Dict[str, Any]) -> str:
    return sql_escape(json.dumps(obj, ensure_ascii=False, separators=(",", ":")))


def emit_insert(
    lines: List[str],
    user_key: str,
    coll: str,
    row_id: str,
    doc: Dict[str, Any],
    created_at: str,
    updated_at: str,
) -> None:
    lines.append(
        f"INSERT INTO bm_owned_row (user_key, coll, id, doc, created_at, updated_at) "
        f"VALUES ({sql_escape(user_key)}, {sql_escape(coll)}, {sql_escape(row_id)}, "
        f"{sql_json(doc)}, {sql_escape(created_at)}, {sql_escape(updated_at)}) "
        f"ON CONFLICT(user_key, coll, id) DO UPDATE SET "
        f"doc = excluded.doc, updated_at = excluded.updated_at;"
    )


def map_kind(k: Optional[str]) -> str:
    k = (k or "time").strip().lower()
    if k in ("time", "expense", "both"):
        if k == "both":
            return "time"
        return k
    return "time"


def map_funding(fs: Optional[str]) -> str:
    fs = (fs or "cash").strip().lower()
    if fs in ("cash", "bank", "credit"):
        return fs
    return "cash"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True, help="Path to rootrecord.db")
    ap.add_argument("--email", required=True, help="Portal email (e.g. rootrecord@outlook.com)")
    ap.add_argument("--user-id", type=int, default=1, help="rr_users.telegram_user_id / local user id (default 1)")
    ap.add_argument("--out", default="-", help="Output SQL path, or - for stdout")
    args = ap.parse_args()

    email = args.email.strip().lower()
    user_key = f"user:{email}"
    uid = int(args.user_id)

    con = sqlite3.connect(args.db)
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    lines: List[str] = []
    lines.append("-- Generated by import_windows_bm_sqlite.py")
    lines.append(f"-- user_key = {user_key}")
    # Remote D1 rejects SQL BEGIN TRANSACTION / COMMIT (use separate statements only).

    # --- business_profiles -> businesses
    cur.execute(
        "SELECT * FROM business_profiles WHERE user_id = ? ORDER BY archived ASC, id ASC",
        (uid,),
    )
    profiles = cur.fetchall()
    default_set = False
    for p in profiles:
        pid = stable_id("businesses", int(p["id"]))
        now = iso_z(p["updated_at"] if p["updated_at"] else p["created_at"])
        created = iso_z(p["created_at"])
        archived = int(p["archived"] or 0)
        is_def = not archived and not default_set
        if is_def:
            default_set = True
        doc = {
            "id": pid,
            "user_id": user_key,
            "name": p["name"] or "Business",
            "legal_name": p["legal_name"] or "",
            "owner": p["owner"] or "",
            "tax_id": p["tax_id"] or "",
            "email": p["email"] or "",
            "phone": p["phone"] or "",
            "website": p["website"] or "",
            "address": p["address"] or "",
            "timezone": p["timezone"] or "system",
            "invoice_notes": p["invoice_notes"] or "",
            "is_default": bool(is_def),
            "created_at": created,
            "updated_at": now,
        }
        emit_insert(lines, user_key, "businesses", pid, doc, created, now)

    # --- work_categories -> categories (preserve sort_order)
    cur.execute(
        "SELECT * FROM work_categories WHERE user_id = ? ORDER BY sort_order ASC, id ASC",
        (uid,),
    )
    cats = cur.fetchall()
    cat_old_to_new: Dict[int, str] = {}
    for c in cats:
        oid = int(c["id"])
        nid = stable_id("categories", oid)
        cat_old_to_new[oid] = nid
        # Legacy `work_categories` has no created_at column.
        created = now_iso()
        updated = created
        so = int(c["sort_order"] or 0)
        # Preserve legacy ordering when many rows share the same sort_order (Windows used id as tie-break).
        cloud_sort = so * 100_000 + oid
        doc = {
            "id": nid,
            "user_id": user_key,
            "name": c["name"] or "Unnamed",
            "color": c["color"] or "#2B8A8F",
            "icon": c["icon"] or "",
            "kind": map_kind(c["kind"]),
            "billable": int(c["billable"] if c["billable"] is not None else 1),
            "archived": int(c["archived"] or 0),
            "sort_order": cloud_sort,
            "default_hourly_cents": c["default_hourly_cents"],
            "created_at": created,
            "updated_at": updated,
        }
        emit_insert(lines, user_key, "categories", nid, doc, created, updated)

    # --- projects
    cur.execute(
        "SELECT * FROM projects WHERE user_id = ? ORDER BY sort_order ASC, id ASC",
        (uid,),
    )
    projs = cur.fetchall()
    proj_old_to_new: Dict[int, str] = {}
    for p in projs:
        oid = int(p["id"])
        nid = stable_id("projects", oid)
        proj_old_to_new[oid] = nid
        # Legacy `projects` has no timestamps.
        created = now_iso()
        updated = created
        so = int(p["sort_order"] or 0)
        cloud_sort = so * 100_000 + oid
        doc = {
            "id": nid,
            "user_id": user_key,
            "name": p["name"] or "Project",
            "client_name": p["client_name"] or "",
            "color": p["color"] or "#5C4D7D",
            "default_hourly_cents": p["default_hourly_cents"],
            "currency": p["currency"] or "USD",
            "notes": p["notes"] or "",
            "archived": int(p["archived"] or 0),
            "sort_order": cloud_sort,
            "created_at": created,
            "updated_at": updated,
        }
        emit_insert(lines, user_key, "projects", nid, doc, created, updated)

    # --- quick_actions -> quick_actions (D1 coll name)
    cur.execute(
        "SELECT * FROM quick_actions WHERE user_id = ? ORDER BY sort_order ASC, id ASC",
        (uid,),
    )
    for q in cur.fetchall():
        oid = int(q["id"])
        nid = stable_id("quick_actions", oid)
        wcid = q["work_category_id"]
        pid = q["project_id"]
        so = int(q["sort_order"] or 0)
        cloud_sort = so * 100_000 + oid
        doc = {
            "id": nid,
            "user_id": user_key,
            "label": q["label"] or "Quick",
            "category_id": cat_old_to_new.get(int(wcid)) if wcid is not None else None,
            "project_id": proj_old_to_new.get(int(pid)) if pid is not None else None,
            "default_description": q["default_description"] or "",
            "sort_order": cloud_sort,
            "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "updated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        }
        emit_insert(
            lines,
            user_key,
            "quick_actions",
            nid,
            doc,
            doc["created_at"],
            doc["updated_at"],
        )

    # --- time entries
    cur.execute(
        "SELECT * FROM rr_time_entries WHERE user_id = ? ORDER BY start_utc ASC",
        (uid,),
    )
    for te in cur.fetchall():
        oid = int(te["id"])
        nid = stable_id("time_entries", oid)
        desc = te["description"] or ""
        notes = te["notes"] or ""
        if notes:
            desc = f"{desc}\n{notes}".strip() if desc else str(notes)
        cat_col = (te["category"] or "work").strip().lower()
        if cat_col == "evaluation" and desc:
            desc = f"[evaluation] {desc}"
        wcid = te["work_category_id"]
        pid = te["project_id"]
        created = iso_z(te["created_at"])
        end = iso_z(te["end_utc"])
        start = iso_z(te["start_utc"])
        doc = {
            "id": nid,
            "user_id": user_key,
            "start_utc": start,
            "end_utc": end,
            "category_id": cat_old_to_new.get(int(wcid)) if wcid is not None else None,
            "project_id": proj_old_to_new.get(int(pid)) if pid is not None else None,
            "description": desc,
            "source": "manual",
            "created_at": created,
            "updated_at": end,
        }
        emit_insert(lines, user_key, "time_entries", nid, doc, created, end)

    # --- income
    cur.execute(
        "SELECT * FROM income_entries WHERE user_id = ? ORDER BY received_at_utc ASC",
        (uid,),
    )
    for inc in cur.fetchall():
        oid = int(inc["id"])
        nid = stable_id("income_entries", oid)
        created = iso_z(inc["created_at"])
        updated = iso_z(inc["updated_at"])
        recv = iso_z(inc["received_at_utc"])
        doc = {
            "id": nid,
            "user_id": user_key,
            "received_at_utc": recv,
            "amount_cents": int(inc["amount_cents"] or 0),
            "currency": inc["currency"] or "USD",
            "description": inc["description"] or "",
            "created_at": created,
            "updated_at": updated,
        }
        wcid = inc["work_category_id"]
        pid = inc["project_id"]
        if wcid is not None:
            doc["category_id"] = cat_old_to_new.get(int(wcid))
        if pid is not None:
            doc["project_id"] = proj_old_to_new.get(int(pid))
        emit_insert(lines, user_key, "income_entries", nid, doc, created, updated)

    # --- expenses
    cur.execute(
        "SELECT * FROM expense_entries WHERE user_id = ? ORDER BY spent_at_utc ASC",
        (uid,),
    )
    for ex in cur.fetchall():
        oid = int(ex["id"])
        nid = stable_id("expense_entries", oid)
        created = iso_z(ex["created_at"])
        spent = iso_z(ex["spent_at_utc"])
        doc = {
            "id": nid,
            "user_id": user_key,
            "spent_at_utc": spent,
            "amount_cents": int(ex["amount_cents"] or 0),
            "currency": ex["currency"] or "USD",
            "description": ex["description"] or "",
            "funding": map_funding(ex["funding_source"]),
            "created_at": created,
            "updated_at": created,
        }
        wcid = ex["work_category_id"]
        pid = ex["project_id"]
        if wcid is not None:
            doc["category_id"] = cat_old_to_new.get(int(wcid))
        if pid is not None:
            doc["project_id"] = proj_old_to_new.get(int(pid))
        emit_insert(lines, user_key, "expense_entries", nid, doc, created, created)

    out = "\n".join(lines) + "\n"
    if args.out == "-":
        print(out, end="")
    else:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(out)
        print(f"Wrote {args.out} ({len(lines)} statements)")


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


if __name__ == "__main__":
    main()
