name = "rootmc-minecraft-map"
main = "src/index.ts"
compatibility_date = "2024-11-01"
workers_dev = true

[vars]
BLUEMAP_LIVE_PROXY_PATH = "/__bluemap-live"
BLUEMAP_ORIGIN = "http://play.rootmc.net:22784"
MAP_PUBLIC_HOST = "map.rootmc.net"
MAP_SERVE_MODE = "hybrid"

[[r2_buckets]]
binding = "BLUEMAP_ASSETS"
bucket_name = "rootmc-bluemap"
